export const slugify = (text) => {
    return text
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)+/g, '');
};

export const SAMPLE_POSTS = [
    {
        id: 1,
        category: 'AI',
        title: 'How AI Is Transforming Brand Identity in 2025',
        desc: 'Explore how artificial intelligence is reshaping the way brands craft their visual identity and messaging.',
        image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🤖',
        readTime: '5 min read',
    },
    {
        id: 2,
        category: 'Design',
        title: 'UX Principles Every Designer Should Master',
        desc: 'A deep dive into the core principles that separate average designers from exceptional ones.',
        image: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🎨',
        readTime: '7 min read',
    },
    {
        id: 3,
        category: 'Branding',
        title: 'Logo Design Trends You Cannot Ignore This Year',
        desc: 'From minimalism to motion — the logo design trends driving brand recognition in the modern era.',
        image: 'https://images.unsplash.com/photo-1600132806370-bf17e65e942f?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '✨',
        readTime: '4 min read',
    },
    {
        id: 4,
        category: 'Web Design',
        title: 'Building Websites That Actually Convert Visitors',
        desc: 'The intersection of beauty and performance — how to design websites that turn traffic into revenue.',
        image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '💻',
        readTime: '6 min read',
    },
    {
        id: 5,
        category: 'Social Media',
        title: 'Content Strategy That Grows Your Following Fast',
        desc: 'Proven frameworks for creating social media content that resonates, engages, and converts.',
        image: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '📱',
        readTime: '5 min read',
    },
    {
        id: 6,
        category: 'Strategy',
        title: 'Why Your Design Process is Costing You Clients',
        desc: 'The hidden inefficiencies in your workflow that are hurting client satisfaction and your bottom line.',
        image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '📊',
        readTime: '8 min read',
    },
    {
        id: 7,
        category: 'AI',
        title: 'The Future of Generative Art in Digital Products',
        desc: 'How generative algorithms are helping visual designers create limitless assets on the fly.',
        image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🔮',
        readTime: '6 min read',
    },
    {
        id: 8,
        category: 'Design',
        title: 'Typography Rules: Setting the Hierarchy Right',
        desc: 'Mastering font sizes, line heights, and letter spacing to improve readability and visual flow.',
        image: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '✍️',
        readTime: '5 min read',
    },
    {
        id: 9,
        category: 'Branding',
        title: 'How to Build a Cohesive Visual Design Language',
        desc: 'A step-by-step guide to defining guidelines that keep your brand consistent across all touchpoints.',
        image: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🏷️',
        readTime: '9 min read',
    },
    {
        id: 10,
        category: 'Web Design',
        title: 'NextJS vs Remix: Which Framework is for You?',
        desc: 'A comparative study of the two most powerful React frameworks for web development in 2026.',
        image: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '⚡',
        readTime: '8 min read',
    },
    {
        id: 11,
        category: 'Social Media',
        title: 'Mastering Short-Form Video Marketing Trends',
        desc: 'Why TikTok, Reels, and YouTube Shorts are crucial components of modern startup growth strategy.',
        image: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🎥',
        readTime: '7 min read',
    },
    {
        id: 12,
        category: 'Strategy',
        title: 'Scaling Design Teams Without Losing Studio Quality',
        desc: 'Best practices for onboarding, workflow integration, and culture preservation in design studios.',
        image: 'https://images.unsplash.com/photo-1512486130939-2c4f79935e4f?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '👥',
        readTime: '10 min read',
    },
    {
        id: 13,
        category: 'AI',
        title: 'Automating Frontend Workflows with LLM Agents',
        desc: 'How agents can streamline styling, asset generation, and initial template rendering processes.',
        image: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🤖',
        readTime: '6 min read',
    },
    {
        id: 14,
        category: 'Design',
        title: 'The Psychology of Color in Dashboard Design',
        desc: 'Choosing correct background, state, and accent colors to reduce cognitive load on users.',
        image: 'https://images.unsplash.com/photo-1561070791-26c113006238?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🎨',
        readTime: '8 min read',
    },
    {
        id: 15,
        category: 'Branding',
        title: 'The Art of Storytelling Through Typography',
        desc: 'Using font selection, customized glyphs, and historical styles to reflect brand history.',
        image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '📖',
        readTime: '5 min read',
    },
    {
        id: 16,
        category: 'Web Design',
        title: 'Designing for the Spatial Web: AR & VR Layouts',
        desc: 'Translating traditional 2D web interfaces into immersive three-dimensional spatial environments.',
        image: 'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🕶️',
        readTime: '7 min read',
    },
    {
        id: 17,
        category: 'Social Media',
        title: 'Building a Developer Community on Twitter/X',
        desc: 'How providing educational resources and updates helps software startups grow natively.',
        image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '💬',
        readTime: '6 min read',
    },
    {
        id: 18,
        category: 'Strategy',
        title: 'How to Pitch Premium Design Services to Enterprise',
        desc: 'Framing value over cost to land five-figure contracts with established corporate clients.',
        image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '💼',
        readTime: '11 min read',
    },
    {
        id: 19,
        category: 'AI',
        title: 'AI-Powered Personalization in E-commerce UI',
        desc: 'Leveraging dynamic layouts that restructure themselves depending on user shopping habits.',
        image: 'https://images.unsplash.com/photo-1684369175833-3d02517865c1?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🛍️',
        readTime: '6 min read',
    },
    {
        id: 20,
        category: 'Design',
        title: 'Designing Accessible Charts and Data Graphics',
        desc: 'Ensuring screen readers, keyboard users, and color-blind visitors can comprehend metrics.',
        image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '📈',
        readTime: '8 min read',
    },
    {
        id: 21,
        category: 'Branding',
        title: 'Rebranding Garuda: The Visual Identity Behind the Wings',
        desc: 'Behind the scenes of updating the Garuda website and design system visuals for modern web.',
        image: 'https://images.unsplash.com/photo-1512486130939-2c4f79935e4f?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🦅',
        readTime: '5 min read',
    },
    {
        id: 22,
        category: 'Web Design',
        title: 'Optimizing NextJS LCP and CLS Performance Metrics',
        desc: 'Advanced strategies to achieve perfect 100/100 Lighthouse performance scores on landing pages.',
        image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🚀',
        readTime: '8 min read',
    },
    {
        id: 23,
        category: 'Social Media',
        title: 'How LinkedIn Newsletters Can Position You as an Expert',
        desc: 'A guide to writing industry insights that attract leads, clients, and partners to your business.',
        image: 'https://images.unsplash.com/photo-1557200134-90327ee9fafa?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '📰',
        readTime: '7 min read',
    },
    {
        id: 24,
        category: 'Strategy',
        title: 'Understanding Product-Market Fit in SaaS Design',
        desc: 'Aligning product styling and user experience to match consumer profiles and expectations.',
        image: 'https://images.unsplash.com/photo-1531538606174-0f90ff5dce83?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🎯',
        readTime: '9 min read',
    },
    {
        id: 25,
        category: 'Web Design',
        title: 'E-commerce Dashboard UI Design: Importance, Steps & Mistakes',
        desc: 'Explore the key factors, design steps, and common mistakes to avoid when creating e-commerce dashboards.',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '📊',
        readTime: '6 min read',
    },
    {
        id: 26,
        category: 'Design',
        title: 'What Does a UX Designer Actually Do? [2024 Guide]',
        desc: 'Learn about the day-to-day responsibilities, skills, and tools of a professional UX designer.',
        image: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '🎨',
        readTime: '7 min read',
    },
    {
        id: 27,
        category: 'Design',
        title: '10 Interaction Design Principles: Your Must-Learn',
        desc: 'A comprehensive guide to the top 10 interaction design principles every modern designer needs to master.',
        image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=800',
        accent: '#fff',
        emoji: '✨',
        readTime: '5 min read',
    },
];
